### ISSUE TITLE
Unrecognized named-value: 'env'

### ISSUE THREAD

**Issue by justusranvier** [lukka/run-cmake#11] opened 2020-04-03 22:48 UTC
Sometime within the last few days all attempts to use run-cmake are failing with this error:

```
Current runner version: '2.168.0'
Operating System
Virtual Environment
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'actions/cache@v1'
Download action repository 'lukka/run-vcpkg@v1'
Download action repository 'lukka/run-cmake@v1'
##[error](Line: 34, Col: 14):
##[error](Line: 34, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.RUNVCPKG_VCPKG_TRIPLET
##[error]Fail to load /home/runner/work/_actions/lukka/run-cmake/v1/action.yml
```

**Comment by lukka** [comment] 2020-04-03 23:07
@justusranvier thanks for reporting this!

It looks like a regression on the test runner?

All [latest validation of the action](https://github.com/lukka/CppBuildTasks-Validation/actions) are using the runner 'Current runner version: '2.165.2''.

I might think of a quick workaround about this anyway.

**Comment by lukka** [comment] 2020-04-04 00:29
@justusranvier looks like the GitHub hosted environments use the runner version `2.165.2`.
I assume this problem is only occurring on a self-hosted runner. Is this correct?

**Comment by justusranvier** [comment] 2020-04-04 00:34
No, it's not self-hosted. Probably github is still in the process of rolling out a new version.

**Comment by lukka** [comment] 2020-04-05 01:36
fixed in latest v1

**Closed by lukka** 2020-04-05 01:36 UTC
